{
    "contributor": {
        "id": 2, 
        "reputation": 0.5, 
        "tokens": 49.0
    }, 
    "id": 1, 
    "stats": {
        "engaged_reputation": 0.0, 
        "evaluations": {
            "0": {
                "reputation": 0.0
            }, 
            "1": {
                "reputation": 0.0
            }
        }, 
        "quality": 0.0, 
        "score": 0.0
    }, 
    "type": "article"
}